### ISSUE TITLE
Required IF

### ISSUE THREAD

**Issue by payswitchpos** [MajAhd/elx_validation#1]
Am using using module and i want do "required if" when validating

**Comment by MajAhd** [comment]
`required_if` and `required_unless` will publish soon

**Comment by payswitchpos** [comment]
> `required_if` and `required_unless` will publish soon
> those are under develop

will be patiently waiting
Thanks

**Comment by MajAhd** [comment]
Please check new version:
Hex: [ElxValidation](https://hex.pm/packages/elx_validation)
Wiki: [Required if](https://github.com/MajAhd/elx_validation/wiki/Required#required-if)
Doc: [Required if](https://hexdocs.pm/elx_validation/api-reference.html#required-if)
hope you enjoy!

**Comment by payswitchpos** [comment]
> Please check new version:
> Hex: [ElxValidation](https://hex.pm/packages/elx_validation)
> Wiki: [Required if](https://github.com/MajAhd/elx_validation/wiki/Required#required-if)
> Doc: [Required if](https://hexdocs.pm/elx_validation/api-reference.html#required-if)
> hope you enjoy!

Thanks so much
